import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(15, 23, 42, 0.85)",
    backdropFilter: "blur(6px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    padding: "24px",
  },
  modal: {
    backgroundColor: "#0F172A",
    border: "1px solid #334155",
    borderRadius: "16px",
    width: "100%",
    maxWidth: "1000px",
    maxHeight: "92vh",
    display: "flex",
    flexDirection: "column",
    boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.7)",
    overflow: "hidden",
  },
  topBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 24px",
    backgroundColor: "#1E293B",
    borderBottom: "1px solid #334155",
  },
  topBarLeft: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  sessionBadge: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "rgba(245, 158, 11, 0.15)",
    color: "#F59E0B",
    fontSize: "12px",
    fontWeight: 600,
    padding: "4px 10px",
    borderRadius: "20px",
  },
  topBarTitle: {
    fontSize: "16px",
    fontWeight: 600,
    color: "#F8FAFC",
  },
  topBarRight: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  timerBadge: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "14px",
    fontFamily: "monospace",
    fontWeight: 700,
    color: "#E2E8F0",
    backgroundColor: "#0F172A",
    padding: "4px 12px",
    borderRadius: "6px",
    border: "1px solid #334155",
  },
  closeBtn: {
    color: "#94A3B8",
    cursor: "pointer",
    padding: "6px",
    borderRadius: "6px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  progressContainer: {
    padding: "12px 24px 8px 24px",
    backgroundColor: "#1E293B",
    borderBottom: "1px solid #334155",
  },
  progressInfo: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "8px",
    fontSize: "13px",
  },
  progressText: {
    color: "#CBD5E1",
  },
  scoreTally: {
    display: "flex",
    gap: "16px",
    fontSize: "12px",
    fontWeight: 600,
  },
  progressBarTrack: {
    width: "100%",
    height: "6px",
    backgroundColor: "#334155",
    borderRadius: "3px",
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: "#3B82F6",
    transition: "width 0.3s ease-in-out",
  },
  bodyContent: {
    padding: "28px",
    overflowY: "auto",
    flex: 1,
  },

  // CONFIG STYLES
  configContainer: {
    maxWidth: "650px",
    margin: "0 auto",
  },
  configHeader: {
    textAlign: "center",
    marginBottom: "28px",
  },
  configTitle: {
    fontSize: "24px",
    fontWeight: 700,
    color: "#F8FAFC",
    marginBottom: "8px",
  },
  configSubtitle: {
    fontSize: "14px",
    color: "#94A3B8",
  },
  configCard: {
    backgroundColor: "#1E293B",
    border: "1px solid #334155",
    borderRadius: "12px",
    padding: "24px",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  label: {
    fontSize: "13px",
    fontWeight: 600,
    color: "#CBD5E1",
  },
  inputField: {
    backgroundColor: "#0F172A",
    border: "1px solid #334155",
    borderRadius: "8px",
    padding: "10px 14px",
    color: "#F8FAFC",
    fontSize: "14px",
    outline: "none",
  },
  selectField: {
    backgroundColor: "#0F172A",
    border: "1px solid #334155",
    borderRadius: "8px",
    padding: "10px 14px",
    color: "#F8FAFC",
    fontSize: "14px",
    outline: "none",
  },
  countBtnRow: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: "10px",
  },
  countBtn: {
    padding: "10px",
    borderRadius: "8px",
    border: "1px solid",
    fontSize: "14px",
    fontWeight: 600,
    cursor: "pointer",
    textAlign: "center",
    transition: "all 0.15s ease",
  },
  infoCallout: {
    backgroundColor: "rgba(59, 130, 246, 0.08)",
    border: "1px solid rgba(59, 130, 246, 0.25)",
    borderRadius: "8px",
    padding: "14px",
    display: "flex",
    gap: "12px",
    fontSize: "13px",
    color: "#CBD5E1",
    lineHeight: "1.6",
  },
  infoCalloutText: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  configActionRow: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "12px",
    marginTop: "12px",
  },
  cancelBtn: {
    padding: "10px 20px",
    borderRadius: "8px",
    backgroundColor: "#334155",
    color: "#F8FAFC",
    fontSize: "14px",
    fontWeight: 600,
    cursor: "pointer",
  },
  startBtn: {
    padding: "10px 24px",
    borderRadius: "8px",
    backgroundColor: "#3B82F6",
    color: "#FFFFFF",
    fontSize: "14px",
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },

  // PRACTICE STYLES
  practiceContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    maxWidth: "900px",
    margin: "0 auto",
  },
  qMetaRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexWrap: "wrap",
  },
  qSubjectBadge: {
    backgroundColor: "rgba(59, 130, 246, 0.15)",
    color: "#3B82F6",
    fontSize: "12px",
    fontWeight: 600,
    padding: "4px 10px",
    borderRadius: "4px",
  },
  qCategoryBadge: {
    backgroundColor: "#334155",
    color: "#E2E8F0",
    fontSize: "12px",
    padding: "4px 8px",
    borderRadius: "4px",
  },
  qTypeBadge: {
    backgroundColor: "#1E293B",
    border: "1px solid #334155",
    color: "#94A3B8",
    fontSize: "11px",
    fontWeight: 600,
    padding: "3px 8px",
    borderRadius: "4px",
  },
  qDiffBadge: {
    fontSize: "12px",
    fontWeight: 600,
  },
  qSourceBadge: {
    fontSize: "11px",
    color: "#94A3B8",
    marginLeft: "auto",
  },
  statementBox: {
    display: "flex",
    gap: "16px",
    backgroundColor: "#1E293B",
    padding: "20px",
    borderRadius: "12px",
    border: "1px solid #334155",
  },
  qIndexIndicator: {
    fontSize: "20px",
    fontWeight: 800,
    color: "#3B82F6",
    flexShrink: 0,
  },
  qText: {
    fontSize: "17px",
    color: "#F8FAFC",
    lineHeight: 1.7,
    whiteSpace: "pre-wrap",
  },
  codeContainer: {
    backgroundColor: "#0A0F1D",
    border: "1px solid #1E293B",
    borderRadius: "8px",
    overflow: "hidden",
  },
  codeHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "8px 14px",
    backgroundColor: "#111827",
    borderBottom: "1px solid #1E293B",
  },
  codeLangBadge: {
    fontSize: "12px",
    fontWeight: 700,
    color: "#38BDF8",
    fontFamily: "monospace",
  },
  copyCodeBtn: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "12px",
    color: "#94A3B8",
    cursor: "pointer",
  },
  codePre: {
    padding: "16px",
    margin: 0,
    fontSize: "14px",
    fontFamily: 'Consolas, Monaco, "Courier New", monospace',
    color: "#E2E8F0",
    lineHeight: 1.6,
    overflowX: "auto",
  },
  codeAnatomyBox: {
    marginTop: "12px",
    borderRadius: "8px",
    backgroundColor: "#0F172A",
    border: "1px solid #1E293B",
    overflow: "hidden",
  },
  codeAnatomyToggleBtn: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 16px",
    backgroundColor: "rgba(255, 255, 255, 0.02)",
    border: "none",
    color: "#93C5FD",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
    textAlign: "left",
  },
  codeAnatomyList: {
    padding: "12px 16px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    borderTop: "1px solid #1E293B",
  },
  codeAnatomyItem: {
    padding: "10px 12px",
    borderRadius: "6px",
    border: "1px solid",
    cursor: "pointer",
    transition: "background-color 0.15s",
  },
  codeAnatomyItemHeader: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "6px",
  },
  codeLineBadge: {
    fontSize: "11px",
    fontWeight: 700,
    padding: "2px 6px",
    borderRadius: "4px",
    backgroundColor: "#1E293B",
    color: "#38BDF8",
    fontFamily: "monospace",
  },
  codeLineText: {
    fontSize: "13px",
    color: "#E2E8F0",
    fontFamily: "Consolas, Monaco, monospace",
  },
  codeExplanationText: {
    fontSize: "13px",
    color: "#94A3B8",
    margin: "0 0 6px 0",
    lineHeight: 1.5,
  },
  traceTag: {
    fontSize: "12px",
    padding: "4px 8px",
    borderRadius: "4px",
    backgroundColor: "rgba(56, 189, 248, 0.1)",
    color: "#38BDF8",
    marginTop: "4px",
    display: "inline-block",
  },
  traceLabel: {
    fontWeight: 700,
  },
  hintContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  hintToggleBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "13px",
    color: "#F59E0B",
    cursor: "pointer",
    alignSelf: "flex-start",
    padding: "4px 8px",
    borderRadius: "4px",
    backgroundColor: "rgba(245, 158, 11, 0.1)",
  },
  hintBox: {
    backgroundColor: "rgba(245, 158, 11, 0.08)",
    border: "1px dashed rgba(245, 158, 11, 0.3)",
    borderRadius: "8px",
    padding: "12px 16px",
    display: "flex",
    alignItems: "center",
    gap: "12px",
    fontSize: "13px",
  },
  progressiveHintItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: "10px",
    padding: "8px 12px",
    backgroundColor: "rgba(245, 158, 11, 0.08)",
    borderRadius: "6px",
    border: "1px solid rgba(245, 158, 11, 0.2)",
  },
  hintBadge: {
    fontSize: "11px",
    fontWeight: 700,
    padding: "2px 6px",
    borderRadius: "4px",
    backgroundColor: "#F59E0B",
    color: "#000000",
    flexShrink: 0,
  },
  hintContentText: {
    fontSize: "13px",
    color: "#F8FAFC",
    lineHeight: 1.5,
  },
  hintLabel: {
    color: "#F59E0B",
    fontWeight: 600,
  },
  hintKeywords: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
  },
  hintKeywordTag: {
    backgroundColor: "#1E293B",
    padding: "3px 8px",
    borderRadius: "4px",
    color: "#CBD5E1",
    fontSize: "12px",
  },

  // INPUT SECTION
  inputSection: {
    backgroundColor: "#1E293B",
    border: "1px solid #334155",
    borderRadius: "12px",
    padding: "24px",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  inputHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  inputLabel: {
    fontSize: "14px",
    fontWeight: 600,
    color: "#94A3B8",
  },
  inputsGrid: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  singleInputRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  inputNumberBadge: {
    fontSize: "14px",
    fontWeight: 700,
    color: "#3B82F6",
    width: "28px",
    flexShrink: 0,
  },
  textInput: {
    flex: 1,
    backgroundColor: "#0F172A",
    border: "2px solid #334155",
    borderRadius: "8px",
    padding: "14px 16px",
    color: "#F8FAFC",
    fontSize: "16px",
    fontWeight: 500,
    outline: "none",
    transition: "border-color 0.15s ease",
  },
  actionBtnRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
    marginTop: "8px",
  },
  unknownBtn: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 20px",
    borderRadius: "8px",
    backgroundColor: "rgba(245, 158, 11, 0.15)",
    border: "1px solid rgba(245, 158, 11, 0.3)",
    color: "#F59E0B",
    fontSize: "15px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  revealBtn: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 20px",
    borderRadius: "8px",
    backgroundColor: "rgba(99, 102, 241, 0.15)",
    border: "1px solid rgba(99, 102, 241, 0.3)",
    color: "#818CF8",
    fontSize: "15px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  submitBtn: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 28px",
    borderRadius: "8px",
    backgroundColor: "#3B82F6",
    color: "#FFFFFF",
    fontSize: "15px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.15s ease",
  },

  // ACTIVE RECALL REVIEW STATE CARD
  reviewStateCard: {
    backgroundColor: "rgba(99, 102, 241, 0.08)",
    border: "1px solid rgba(99, 102, 241, 0.25)",
    borderRadius: "10px",
    padding: "16px 20px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  reviewStateHeader: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  reviewStateTitle: {
    fontSize: "14px",
    fontWeight: 700,
    color: "#A5B4FC",
  },
  reviewStateBadge: {
    fontSize: "11px",
    fontWeight: 700,
    padding: "2px 8px",
    borderRadius: "4px",
    backgroundColor: "rgba(99, 102, 241, 0.2)",
    color: "#C7D2FE",
    marginLeft: "auto",
  },
  reviewStateGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "12px",
  },
  reviewStateItem: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    backgroundColor: "rgba(15, 23, 42, 0.4)",
    padding: "10px 12px",
    borderRadius: "8px",
    border: "1px solid rgba(255, 255, 255, 0.05)",
  },
  reviewStateItemLabel: {
    fontSize: "11px",
    color: "#94A3B8",
  },
  reviewStateItemValue: {
    fontSize: "14px",
    fontWeight: 700,
    color: "#F8FAFC",
  },

  // FEEDBACK SECTION
  feedbackSection: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  feedbackBanner: {
    display: "flex",
    gap: "16px",
    alignItems: "center",
    padding: "18px 24px",
    borderRadius: "12px",
    border: "1.5px solid",
  },
  bannerIconBox: {
    flexShrink: 0,
  },
  bannerContent: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  bannerTitle: {
    fontSize: "18px",
    fontWeight: 700,
  },
  bannerDesc: {
    fontSize: "14px",
    color: "#E2E8F0",
  },
  fuzzyNotice: {
    color: "#38BDF8",
    marginLeft: "8px",
    fontSize: "12px",
  },
  compareContainer: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
  },
  compareCard: {
    backgroundColor: "#1E293B",
    border: "1px solid #334155",
    borderRadius: "8px",
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  compareLabel: {
    fontSize: "12px",
    fontWeight: 600,
    color: "#94A3B8",
  },
  userAnswerVal: {
    fontSize: "16px",
    fontWeight: 600,
    color: "#F8FAFC",
    wordBreak: "break-all",
  },
  groundTruthVal: {
    fontSize: "16px",
    fontWeight: 700,
    color: "var(--color-success)",
    wordBreak: "break-all",
  },
  groundTruthBox: {
    backgroundColor: "rgba(16, 185, 129, 0.05)",
    border: "1px solid rgba(16, 185, 129, 0.3)",
    borderRadius: "10px",
    padding: "18px",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  boxTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  groundTruthTitle: {
    fontSize: "14px",
    fontWeight: 700,
    color: "var(--color-success)",
  },
  explanationText: {
    fontSize: "14px",
    color: "#CBD5E1",
    lineHeight: 1.75,
    margin: 0,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  aiBox: {
    backgroundColor: "rgba(168, 85, 247, 0.05)",
    border: "1px solid rgba(168, 85, 247, 0.3)",
    borderRadius: "10px",
    padding: "18px",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  aiTitle: {
    fontSize: "14px",
    fontWeight: 700,
    color: "#A855F7",
  },
  aiNoticeBadge: {
    fontSize: "11px",
    color: "#94A3B8",
    marginLeft: "auto",
  },
  variationNoteBox: {
    marginTop: "6px",
    padding: "10px 12px",
    borderRadius: "6px",
    backgroundColor: "rgba(168, 85, 247, 0.1)",
    fontSize: "12px",
    color: "#E9D5FF",
    lineHeight: 1.5,
  },
  nextActionRow: {
    display: "flex",
    justifyContent: "flex-end",
    marginTop: "10px",
  },
  nextBtn: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "14px 32px",
    borderRadius: "8px",
    backgroundColor: "#3B82F6",
    color: "#FFFFFF",
    fontSize: "16px",
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 4px 14px rgba(59, 130, 246, 0.4)",
  },

  // SUMMARY STYLES
  summaryContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "28px",
    maxWidth: "800px",
    margin: "0 auto",
  },
  summaryHero: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    gap: "12px",
    padding: "24px 0",
  },
  trophyIconBox: {
    width: "72px",
    height: "72px",
    borderRadius: "36px",
    backgroundColor: "rgba(245, 158, 11, 0.15)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "8px",
  },
  summaryTitle: {
    fontSize: "26px",
    fontWeight: 800,
    color: "#F8FAFC",
  },
  summarySubtitle: {
    fontSize: "15px",
    color: "#94A3B8",
  },
  accuracyCircle: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: "130px",
    height: "130px",
    borderRadius: "65px",
    backgroundColor: "#1E293B",
    border: "3px solid #3B82F6",
    marginTop: "12px",
  },
  accuracyNumber: {
    fontSize: "32px",
    fontWeight: 800,
    color: "#3B82F6",
  },
  accuracyLabel: {
    fontSize: "12px",
    color: "#94A3B8",
  },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: "14px",
  },
  summaryStatCard: {
    backgroundColor: "#1E293B",
    border: "1px solid #334155",
    borderRadius: "10px",
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    textAlign: "center",
  },
  statLabel: {
    fontSize: "12px",
    color: "#94A3B8",
    fontWeight: 600,
  },
  statVal: {
    fontSize: "20px",
    fontWeight: 700,
    color: "#F8FAFC",
  },
  reviewListSection: {
    display: "flex",
    flexDirection: "column",
    gap: "14px",
  },
  reviewListTitle: {
    fontSize: "16px",
    fontWeight: 700,
    color: "#F8FAFC",
  },
  reviewCards: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  reviewCard: {
    backgroundColor: "#1E293B",
    border: "1px solid #334155",
    borderLeftWidth: "5px",
    borderRadius: "8px",
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  reviewCardHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "13px",
  },
  reviewQIndex: {
    fontWeight: 700,
    color: "#3B82F6",
  },
  reviewQSubj: {
    color: "#94A3B8",
  },
  reviewQCat: {
    color: "#CBD5E1",
    fontWeight: 500,
  },
  reviewStatusBadge: {
    marginLeft: "auto",
    fontWeight: 700,
    fontSize: "12px",
  },
  reviewQText: {
    fontSize: "14px",
    color: "#F8FAFC",
    lineHeight: 1.5,
  },
  reviewAnswersRow: {
    display: "flex",
    gap: "24px",
    fontSize: "13px",
    backgroundColor: "#0F172A",
    padding: "10px 14px",
    borderRadius: "6px",
  },
  reviewAnswerItem: {
    display: "flex",
    gap: "6px",
  },
  reviewAnswerKey: {
    color: "#94A3B8",
  },
  reviewAnswerVal: {
    color: "#CBD5E1",
  },
  summaryActionRow: {
    display: "flex",
    justifyContent: "center",
    gap: "16px",
    paddingTop: "16px",
  },
  newSessionBtn: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 24px",
    borderRadius: "8px",
    backgroundColor: "#3B82F6",
    color: "#FFFFFF",
    fontSize: "15px",
    fontWeight: 600,
    cursor: "pointer",
  },
  doneBtn: {
    padding: "12px 24px",
    borderRadius: "8px",
    backgroundColor: "#334155",
    color: "#F8FAFC",
    fontSize: "15px",
    fontWeight: 600,
    cursor: "pointer",
  },
  errorAlert: {
    backgroundColor: "rgba(239, 68, 68, 0.15)",
    border: "1px solid var(--color-danger)",
    color: "var(--color-danger)",
    borderRadius: "8px",
    padding: "12px 16px",
    fontSize: "14px",
  },
  loadingBox: {
    padding: "48px",
    textAlign: "center",
    color: "#94A3B8",
  },

  // Phase 8 Interactive Code & Hints Styles
  codeHintText: {
    fontSize: "11px",
    color: "#94A3B8",
  },
  codeLinesContainer: {
    display: "flex",
    flexDirection: "column",
    backgroundColor: "#0A0F1D",
  },
  codeLineRow: {
    display: "flex",
    alignItems: "center",
    padding: "2px 8px",
    transition: "background-color 0.15s ease",
  },
  codeLineNumber: {
    width: "36px",
    flexShrink: 0,
    fontFamily: "monospace",
    fontSize: "13px",
    textAlign: "right",
    paddingRight: "12px",
    userSelect: "none",
  },
  codeLineContent: {
    margin: 0,
    padding: 0,
    fontFamily: 'Consolas, Monaco, "Courier New", monospace',
    fontSize: "13.5px",
    color: "#E2E8F0",
    lineHeight: 1.6,
    whiteSpace: "pre",
    flex: 1,
  },
  codeLineLoadingTag: {
    fontSize: "11px",
    color: "#38BDF8",
    marginLeft: "auto",
  },
  inlineAnatomyCard: {
    margin: "4px 12px 10px 36px",
    padding: "12px 16px",
    backgroundColor: "#0F172A",
    border: "1.5px solid #38BDF8",
    borderRadius: "8px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  inlineAnatomyHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1px solid rgba(56, 189, 248, 0.2)",
    paddingBottom: "6px",
  },
  inlineLineSnippet: {
    fontSize: "12px",
    color: "#CBD5E1",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    padding: "2px 6px",
    borderRadius: "4px",
    marginLeft: "8px",
  },
  closeInlineBtn: {
    background: "none",
    border: "none",
    color: "#94A3B8",
    cursor: "pointer",
    fontSize: "14px",
  },
  inlineLoadingText: {
    padding: "8px 0",
    color: "#94A3B8",
    fontSize: "13px",
  },
  inlineAnatomyBody: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    fontSize: "13px",
    lineHeight: 1.5,
  },
  anatomyMeaning: {
    color: "#E2E8F0",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  anatomySyntaxRow: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    flexWrap: "wrap",
  },
  anatomyLabel: {
    color: "#94A3B8",
    fontSize: "12px",
  },
  anatomyTag: {
    backgroundColor: "rgba(56, 189, 248, 0.15)",
    color: "#38BDF8",
    padding: "2px 8px",
    borderRadius: "4px",
    fontSize: "12px",
  },
  anatomyContext: {
    color: "#CBD5E1",
    fontSize: "12.5px",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  anatomyExamTip: {
    color: "#FCD34D",
    backgroundColor: "rgba(245, 158, 11, 0.1)",
    padding: "6px 10px",
    borderRadius: "6px",
    border: "1px solid rgba(245, 158, 11, 0.2)",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  anatomyRole: {
    color: "#F8FAFC",
    backgroundColor: "rgba(15, 23, 42, 0.5)",
    padding: "8px 12px",
    borderRadius: "6px",
    borderLeft: "3px solid #38BDF8",
    fontSize: "13px",
  },
  anatomyBehavior: {
    color: "#E2E8F0",
    backgroundColor: "rgba(15, 23, 42, 0.5)",
    padding: "8px 12px",
    borderRadius: "6px",
    borderLeft: "3px solid #34D399",
    fontSize: "13px",
  },
  anatomyHint: {
    color: "#93C5FD",
    backgroundColor: "rgba(59, 130, 246, 0.1)",
    padding: "6px 10px",
    borderRadius: "6px",
    border: "1px solid rgba(59, 130, 246, 0.25)",
    fontSize: "12.5px",
  },
  syntaxTermPillBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    backgroundColor: "rgba(56, 189, 248, 0.15)",
    color: "#38BDF8",
    border: "1px solid rgba(56, 189, 248, 0.35)",
    padding: "2px 8px",
    borderRadius: "6px",
    fontSize: "12px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  syntaxTermKeyHint: {
    fontSize: "10.5px",
    color: "#94A3B8",
    fontWeight: 400,
  },
  statusPendingBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    fontSize: "12px",
    fontWeight: 600,
    color: "#38BDF8",
    backgroundColor: "rgba(56, 189, 248, 0.12)",
    border: "1px solid rgba(56, 189, 248, 0.3)",
    padding: "2px 8px",
    borderRadius: "6px",
  },
  statusReadyBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    fontSize: "12px",
    fontWeight: 600,
    color: "#10B981",
    backgroundColor: "rgba(16, 185, 129, 0.12)",
    border: "1px solid rgba(16, 185, 129, 0.3)",
    padding: "2px 8px",
    borderRadius: "6px",
  },
  statusFailedBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    fontSize: "12px",
    fontWeight: 600,
    color: "#EF4444",
    backgroundColor: "rgba(239, 68, 68, 0.12)",
    border: "1px solid rgba(239, 68, 68, 0.3)",
    padding: "2px 8px",
    borderRadius: "6px",
  },
  statusRegenBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    fontSize: "12px",
    fontWeight: 600,
    color: "#F59E0B",
    backgroundColor: "rgba(245, 158, 11, 0.12)",
    border: "1px solid rgba(245, 158, 11, 0.3)",
    padding: "2px 8px",
    borderRadius: "6px",
  },

  // AI TUTOR SECTION
  aiTutorContainer: {
    backgroundColor: "#1E1B4B",
    border: "1.5px solid #818CF8",
    borderRadius: "12px",
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  aiTutorHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  aiTutorTitle: {
    fontSize: "16px",
    fontWeight: 700,
    color: "#C7D2FE",
  },
  aiSourceBadge: {
    fontSize: "11px",
    fontWeight: 700,
    backgroundColor: "#4338CA",
    color: "#E0E7FF",
    padding: "2px 8px",
    borderRadius: "4px",
  },
  loadAIBtn: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "#4F46E5",
    color: "#FFFFFF",
    border: "none",
    borderRadius: "6px",
    padding: "6px 12px",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
  },
  aiLoadingBox: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    color: "#C7D2FE",
    fontSize: "14px",
    padding: "12px",
  },
  aiTutorContent: {
    display: "flex",
    flexDirection: "column",
    gap: "14px",
  },
  aiSummaryBadge: {
    fontSize: "15px",
    fontWeight: 700,
    color: "#F8FAFC",
    backgroundColor: "rgba(129, 140, 248, 0.15)",
    padding: "10px 14px",
    borderRadius: "8px",
    border: "1px solid rgba(129, 140, 248, 0.3)",
  },
  aiConflictBox: {
    backgroundColor: "rgba(245, 158, 11, 0.15)",
    border: "1.5px solid #F59E0B",
    borderRadius: "8px",
    padding: "14px",
  },
  aiWhyWrongBox: {
    backgroundColor: "rgba(239, 68, 68, 0.1)",
    border: "1px solid rgba(239, 68, 68, 0.25)",
    borderRadius: "8px",
    padding: "12px",
  },
  aiKeyPointBox: {
    backgroundColor: "rgba(59, 130, 246, 0.1)",
    border: "1px solid rgba(59, 130, 246, 0.25)",
    borderRadius: "8px",
    padding: "12px",
  },
  aiCodeTraceBox: {
    backgroundColor: "rgba(15, 23, 42, 0.7)",
    border: "1px solid #334155",
    borderRadius: "8px",
    padding: "12px",
  },
  codeTracePre: {
    margin: "10px 0 0 0",
    fontFamily: "'Fira Code', 'Consolas', 'Courier New', monospace",
    fontSize: "13px",
    color: "#38BDF8",
    backgroundColor: "#0B1120",
    padding: "14px 16px",
    borderRadius: "8px",
    border: "1px solid #1E293B",
    lineHeight: 1.75,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    overflowX: "auto",
  },
  aiPitfallsBox: {
    backgroundColor: "rgba(245, 158, 11, 0.1)",
    border: "1px solid rgba(245, 158, 11, 0.25)",
    borderRadius: "8px",
    padding: "12px",
  },
  aiStudyTipsBox: {
    backgroundColor: "rgba(16, 185, 129, 0.1)",
    border: "1px solid rgba(16, 185, 129, 0.25)",
    borderRadius: "8px",
    padding: "12px",
  },
  aiSectionText: {
    margin: "6px 0 0 0",
    fontSize: "14px",
    color: "#E2E8F0",
    lineHeight: 1.75,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  variationRow: {
    display: "flex",
    justifyContent: "flex-end",
    marginTop: "6px",
  },
  drillStartBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    backgroundColor: "rgba(245, 158, 11, 0.15)",
    border: "1.5px solid #F59E0B",
    color: "#FDE68A",
    borderRadius: "8px",
    padding: "11px 18px",
    fontSize: "14px",
    fontWeight: 700,
    cursor: "pointer",
    width: "100%",
    transition: "all 0.15s ease",
  },
  drillSaveContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    marginTop: "4px",
  },
  saveDrillBtn: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "rgba(16, 185, 129, 0.15)",
    border: "1px solid #10B981",
    color: "#A7F3D0",
    borderRadius: "6px",
    padding: "8px 14px",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
  },
  drillSavedBadge: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    color: "#10B981",
    fontSize: "13px",
    fontWeight: 600,
    backgroundColor: "rgba(16, 185, 129, 0.1)",
    padding: "6px 12px",
    borderRadius: "6px",
  },
};
